spring:
  redis:
    host: devredis.jshuii.com
    port: 6385
    password: ReyH2WMVtn0KalCA0v6385
    database: 7
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 1