CREATE TABLE IF NOT EXISTS `goods_summary` (
	`id`  bigint NOT NULL ,
	`order_no`  varchar(50) NULL COMMENT '订单编号' ,
	`shop_name`  varchar(50) NULL COMMENT '门店名称' ,
	`shop_id`  bigint NULL COMMENT '门店id' ,
	`shop_code`  varchar(20) NULL COMMENT '门店code' ,
	`goods_code`  varchar(20) NULL COMMENT '商品code' ,
	`goods_name`  varchar(50) NULL COMMENT '商品名称' ,
	`reserved_count`  int(11) NULL DEFAULT 0 COMMENT '预订数量' ,
	`delivery_date`  timestamp NULL COMMENT '配送日期' ,
	`reserved_date`  timestamp NULL COMMENT '预订日期' ,
	`delivery_time`  time NULL COMMENT '送达时间' ,
	`status` tinyint(2) NULL COMMENT '订单状态 1正常 0退款',
	`is_deleted`  tinyint(2) NULL DEFAULT 0 COMMENT '是否删除（0否、1是）' ,
	`create_time`  timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
	PRIMARY KEY (`id`),
	KEY `idx_goods_code` (`goods_code`) USING BTREE
)COMMENT='商品汇总';

CREATE TABLE IF NOT EXISTS `order_set_detail_bf` (
  `id` bigint(20) NOT NULL,
  `type` tinyint(2) DEFAULT '0' COMMENT '状态 0=早餐，1=午餐',
  `detail_set_no` varchar(50) DEFAULT NULL COMMENT '集单单号',
  `detail_set_no_description` varchar(100) DEFAULT NULL COMMENT '集单号描述',
  `detail_delivery_date` date DEFAULT NULL COMMENT '配送日期',
  `delivery_start_time` time DEFAULT NULL COMMENT '配送开始时间',
  `delivery_end_time` time DEFAULT NULL COMMENT '配送结束时间',
  `detail_delivery_address` varchar(200) DEFAULT NULL COMMENT '订单详细配送地址',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '门店id',
  `building_id` bigint(20) DEFAULT NULL COMMENT '楼宇id',
  `building_abbreviation` varchar(50) DEFAULT NULL COMMENT '楼宇简称',
  `delivery_floor` varchar(50) DEFAULT NULL COMMENT '楼层',
  `company_id` bigint(20) DEFAULT NULL COMMENT '公司id',
  `company_abbreviation` varchar(50) DEFAULT NULL COMMENT '公司简称/房间号',
  `goods_sum` int(4) DEFAULT NULL COMMENT '子集单中商品总数量',
  `actual_pay_amount` decimal(10,2) DEFAULT NULL COMMENT '实付总金额',
  `is_print` tinyint(1) DEFAULT '0' COMMENT '是否已打印 1是 0否',
  `status` tinyint(2) DEFAULT '1' COMMENT '状态 1待生产 2生产中 3已完成',
  `distribution_status` tinyint(2) DEFAULT NULL COMMENT '配送状态 -1初始化 0已派单 1已接单 2已到店 3已取件 4已送达',
  `is_push` tinyint(1) DEFAULT '0' COMMENT '是否已发MQ 1是 0否',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除 1是 0否',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人  账号_名字组合',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '最后修改人 账号_名字组合',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='集单表-早餐';

CREATE TABLE IF NOT EXISTS `order_set_detail_goods_bf` (
  `id` bigint(20) NOT NULL,
  `detail_set_no` varchar(50) DEFAULT NULL COMMENT '子集单单号',
  `order_no` varchar(50) DEFAULT NULL COMMENT '订单编号',
  `couplet_no` varchar(50) DEFAULT NULL COMMENT '订单联的编号',
  `user_id` bigint(20) DEFAULT NULL COMMENT '订餐用户id',
  `user_name` varchar(50) DEFAULT NULL COMMENT '订餐用户名字',
  `user_phone` varchar(20) DEFAULT NULL COMMENT '订餐用户手机号',
  `goods_code` varchar(20) DEFAULT NULL COMMENT '商品编号',
  `goods_name` varchar(50) DEFAULT NULL COMMENT '商品名字',
  `goods_number` int(5) DEFAULT NULL COMMENT '数量',
  `actual_pay_amount` decimal(10,2) DEFAULT NULL COMMENT '单件商品实付金额',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除 1是 0否',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人  账号_名字组合',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '最后修改人 账号_名字组合',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_detail_set_no` (`detail_set_no`) USING BTREE,
  KEY `idx_order_no` (`order_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='集单商品明细表-早餐';
