spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dbtest.jshuii.com:3306/milisong_scmpre?characterEncoding=utf-8&amp;useOldAliasMetadataBehavior=true&amp;autoReconnectForPools=true;useSSL=true
    username: milisong_scm
    password: HWEMorWbTEZ+DGBqLRskFZeul06gZ5pWRAiaSHNk9gg=
    type: com.farmland.core.db.SecureDruidDataSource

#数据库主键生产策略
idworker:
  workerId: 0

mybatis:
  mapper-locations: classpath*:mapper/*.xml,mapper/base/*.xml
  configuration:
    mapUnderscoreToCamelCase: true