server:
  port: 30002
management:
# spring admin检测 默认开启
  health:
    defaults:
      enabled: false

spring:
  boot:
    admin:
      client:
        url: http://localhost:60100
        auto-deregistration: true
  cloud:
    config:
      override-none: true
ecm:
  shoponsale:
    goods-url:  http://devmls-api.jshuii.com/v1/goods/set-onsale-goods
    goodsStock-url: http://devmls-bapi.jshuii.com/v1/goods/set-onsale-stock
    goodsStockList-url: http://devmls-bapi.jshuii.com/v1/goods/set-onsale-stock-list
    buildingList-url: http://devmls-api.jshuii.com/v1/goods/building-list
    orderList-url: http://devmls-api.jshuii.com/v1/order/get-order-details
    goods-default-count:  200

file:
  oss:
#  本地备份路径
    localBackupPath: /data/files/images/milisong/
#    oss上传路径
    uploadUrl: http://devoss.jshuii.com/v1/uploadFileService/uploadByte
#    查询路径
    viewUrl: http://jshuii-dev.oss-cn-hangzhou.aliyuncs.com
#the maximum size of single file (unit:MB)
    maxSingleFileSize: 4MB
#file format
    format: txt,word,excel,jpg,png,gif,pdf
#导出路径
  export:
    path: /data/milisong/export/

# LBS公共服务的地址
lbs:
  pointServiceUrl: http://devmls-lbs.jshuii.com/lbs/point
  convertServiceUrl: http://devmls-lbs.jshuii.com/lbs/convert/baidu2gcj02

# 压缩url
url:
  compress-url: http://api.weibo.com/2/short_url/shorten.json?source=2849184197&url_long={url}

# sms通知
#sms:
#  send-url: http://testsms.jshuii.com/api/v1/MobileSendService/sendSms
# sms通知
sms:
  sendUrl: http://testsms.jshuii.com/api/v1/MobileSendService/sendSms
  
# oms订单检查
oms:
  checkUrl: http://premls-omsapiin.jshuii.com/v1/OrderService/getDeliveryNos
  notifyUrl: http://premls-omsapiin.jshuii.com/v1/order/repair-order-mq
