spring:
  redis:
    host: 10.18.75.34
    password: ReyH2WMVtn0KalCA0v6387
    port: 6387
    timeout: 1000
    database: 3
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 1

redisson:
  address: redis://10.18.75.34:6387
  password: ReyH2WMVtn0KalCA0v6387
  database: 3