swagger:
  conf:
    desc: api地址：http://${swagger.conf.host}/
    service-url: http://${swagger.conf.host}/
    title: 米立早餐${swagger.conf.group-name}接口
    host: devmls-bscmapi.jshuii.com
    #host: localhost:31000
    group-name: scm-web
    base-package: com.milisong.breakfast.scm.rest
    version: 1.0