package com.milisong.pms.prom.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ActivityUserRedPacket implements Serializable {

    private Long id;

    private Long activityId;

    private Byte type;

    private Byte launchType;

    private Long launchId;

    private Long userId;

    private String openId;

    private String nickName;

    private String headPortraitUrl;

    private Byte clickCount;

    private Byte isSuccess;

    private BigDecimal amount;

    private Byte players;

    private Byte valid;

    private Byte isShare;

    private Byte clickLimit;

    private Date startDate;

    private Date endDate;

    private Byte businessLine;

    private Date createTime;

    private Date updateTime;

    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getActivityId() {
        return activityId;
    }

    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.nick_name
     *
     * @param nickName the value for t_activity_user_red_packet.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.head_portrait_url
     *
     * @return the value of t_activity_user_red_packet.head_portrait_url
     *
     * @mbggenerated
     */
    public String getHeadPortraitUrl() {
        return headPortraitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.head_portrait_url
     *
     * @param headPortraitUrl the value for t_activity_user_red_packet.head_portrait_url
     *
     * @mbggenerated
     */
    public void setHeadPortraitUrl(String headPortraitUrl) {
        this.headPortraitUrl = headPortraitUrl == null ? null : headPortraitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.click_count
     *
     * @return the value of t_activity_user_red_packet.click_count
     *
     * @mbggenerated
     */
    public Byte getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.click_count
     *
     * @param clickCount the value for t_activity_user_red_packet.click_count
     *
     * @mbggenerated
     */
    public void setClickCount(Byte clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.is_success
     *
     * @return the value of t_activity_user_red_packet.is_success
     *
     * @mbggenerated
     */
    public Byte getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.is_success
     *
     * @param isSuccess the value for t_activity_user_red_packet.is_success
     *
     * @mbggenerated
     */
    public void setIsSuccess(Byte isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.amount
     *
     * @return the value of t_activity_user_red_packet.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.amount
     *
     * @param amount the value for t_activity_user_red_packet.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.players
     *
     * @return the value of t_activity_user_red_packet.players
     *
     * @mbggenerated
     */
    public Byte getPlayers() {
        return players;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.players
     *
     * @param players the value for t_activity_user_red_packet.players
     *
     * @mbggenerated
     */
    public void setPlayers(Byte players) {
        this.players = players;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.valid
     *
     * @return the value of t_activity_user_red_packet.valid
     *
     * @mbggenerated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.valid
     *
     * @param valid the value for t_activity_user_red_packet.valid
     *
     * @mbggenerated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.is_share
     *
     * @return the value of t_activity_user_red_packet.is_share
     *
     * @mbggenerated
     */
    public Byte getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.is_share
     *
     * @param isShare the value for t_activity_user_red_packet.is_share
     *
     * @mbggenerated
     */
    public void setIsShare(Byte isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.click_limit
     *
     * @return the value of t_activity_user_red_packet.click_limit
     *
     * @mbggenerated
     */
    public Byte getClickLimit() {
        return clickLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.click_limit
     *
     * @param clickLimit the value for t_activity_user_red_packet.click_limit
     *
     * @mbggenerated
     */
    public void setClickLimit(Byte clickLimit) {
        this.clickLimit = clickLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.start_date
     *
     * @return the value of t_activity_user_red_packet.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.start_date
     *
     * @param startDate the value for t_activity_user_red_packet.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.end_date
     *
     * @return the value of t_activity_user_red_packet.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.end_date
     *
     * @param endDate the value for t_activity_user_red_packet.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.create_time
     *
     * @return the value of t_activity_user_red_packet.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.create_time
     *
     * @param createTime the value for t_activity_user_red_packet.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_user_red_packet.update_time
     *
     * @return the value of t_activity_user_red_packet.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_user_red_packet.update_time
     *
     * @param updateTime the value for t_activity_user_red_packet.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public Byte getLaunchType() {
        return launchType;
    }

    public void setLaunchType(Byte launchType) {
        this.launchType = launchType;
    }

    public Long getLaunchId() {
        return launchId;
    }

    public void setLaunchId(Long launchId) {
        this.launchId = launchId;
    }

    public Byte getBusinessLine() {
        return businessLine;
    }

    public void setBusinessLine(Byte businessLine) {
        this.businessLine = businessLine;
    }
}