server:
  port: 30040

spring:
  boot:
    admin:
      client:
        url: http://172.16.14.60:60100
        instance:
          prefer-ip: true
        auto-deregistration: true
  cloud:
    config:
      override-none: true

ribbon:
  ReadTimeout:  10000
  SocketTimeout:  10000

oms:
  sys:
    scmBaseUrl: http://mls-dmsapiin.jshuii.com
    delayQueue:
      orderCallbackUrl: http://mls-omsapiin.jshuii.com/v1/order/expired-order-cancel
      virtualOrderCallbackUrl: http://mls-omsapiin.jshuii.com/v1/order/expired-virtual-order-cancel
      baseUrl: http://mls-dqsapi.jshuii.com
    localCache:
      expireTime: 60

scm:
  sys:
    scmBfRedisUrl: http://mls-bscmapiin.jshuii.com/redis/get
    scmBfRedisUrlincr: http://mls-bscmapiin.jshuii.com/redis/incr
    scmBfRedisUrlset: http://mls-bscmapiin.jshuii.com/redis/set
# sms通知
sms:
  sendUrl: http://sms.jshuii.com/api/v1/MobileSendService/sendSms
  out-of-stock-msg: 亲，很抱歉今天部分商品缺货，暂时用其他商品给您替代。我们将在24小时内为您退款，感谢您的谅解！
  send-time: "07:30"