server:
  port: 30040

spring:
  boot:
    admin:
      client:
        url: http://172.16.14.60:60100
        instance:
          prefer-ip: true
        auto-deregistration: true
  cloud:
    config:
      override-none: true

ribbon:
  ReadTimeout:  10000
  SocketTimeout:  10000

oms:
  sys:
    scmBaseUrl: http://mls-dmsapiin.jshuii.com
    delayQueue:
      orderCallbackUrl: http://mls-omsapiin.jshuii.com/v1/order/expired-order-cancel
      virtualOrderCallbackUrl: http://mls-omsapiin.jshuii.com/v1/order/expired-virtual-order-cancel
      baseUrl: http://mls-dqsapi.jshuii.com
    localCache:
      expireTime: 60
