spring:
  rabbitmq:
    addresses: amqp://mq.jshuii.com:5672
    username: milisong-omsuser
    password: 7TklcO2O7n6v3X4GMg
  cloud:
    stream:
      # 设置默认的binder
      default-binder: oms
      binders:
        oms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到ecm的host和exchange
                virtual-host: milisong-oms
      bindings:
        # 订单消费
        order_status_input:
          binder: oms
          destination: OMS_ORDER_STATUS
          group: oms_group
        order_payment_input:
          binder: oms
          destination: OMS_PAYMENT
          group: oms_group
          # 订单生产
        order_output:
          binder: oms
          destination: OMS_ORDER
        payment_output:
          binder: oms
          destination: OMS_PAYMENT
        cancel_output:
          binder: oms
          destination: OMS_CANCEL
        refund_output:
          binder: oms
          destination: OMS_REFUND
      rabbit:
        bindings:
          # 订单消费的个性化配置
          order_status_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: OMS_ORDER_ORDER_SET_DLX
          order_payment_input:
            consumer:
              exchangeType: topic
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: OMS_ORDER_PAYMENT_DLX
          order_output:
            producer:
              exchangeType: fanout
          payment_output:
            producer:
              exchangeType: topic
              routingKeyExpression: headers.businessLine
          cancel_output:
            producer:
              exchangeType: fanout
          refund_output:
            producer:
              exchangeType: fanout

