spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1n8wbp09b4n7w2v.mysql.rds.aliyuncs.com:3306/milisong_scm?characterEncoding=utf-8&amp;useOldAliasMetadataBehavior=true&amp;autoReconnectForPools=true;useSSL=true
    username: milisong_scm_user
    password: TBQoaOyDzmULcznRZzJSF8oF0bMr0RvCuRe+N7LLqYk=
    type: com.farmland.core.db.SecureDruidDataSource

#数据库主键生产策略
#idworker:
#  workerId: 0

mybatis:
  mapper-locations: classpath*:mapper/*.xml,mapper/base/*.xml
  configuration:
    mapUnderscoreToCamelCase: true