spring:
  rabbitmq:
    addresses: amqp://mq.jshuii.com:5672
    username: milisong-scmuser
    password: vO7f8cvsdsg6b5b
  cloud:
    stream:
      # 设置默认的binder
      default-binder: scm
      binders:
        oms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-oms
        ecm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-ecm
        scm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-scm