spring:
  redis:
    host: devredis.jshuii.com
    password: ReyH2WMVtrf0vwerwf6386
    port: 6386
    timeout: 1000
    database: 14
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 1

redisson:
  address: redis://devredis.jshuii.com:6386
  password: ReyH2WMVtrf0vwerwf6386
  database: 14
