spring:
  rabbitmq:
    addresses: amqp://mqdev.jshuii.com:5672
    username: milisong-scmuser
    password: vO7kZK63W8cv
  cloud:
    stream:
      # 设置默认的binder
      default-binder: dms
      binders:
        scm:
          type: rabbit
          environment:
           spring:
             rabbitmq:
               # 连接到scm的host和exchange
               virtual-host: milisong-scm
        dms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到dms的host和exchange
                virtual-host: milisong-scm-breakfast