spring:
  rabbitmq:
    addresses: amqp://mq.jshuii.com:5672
    username: milisong-posuser
    password: Z0jw9IookFS33k22OZ
  cloud:
    stream:
      # 设置默认的binder
      default-binder: pos
      binders:
        scm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-scm
        pos:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-pos
        oms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-oms