spring:
  redis:
    host: redis01.jshuii.com
    port: 6386
    password: A@c0KcSx7Tnthr5L
    database: 5
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 1

redisson:
  address: redis://redis01.jshuii.com:6386
  password: A@c0KcSx7Tnthr5L
  database: 5
  
# redis超时通知    
redisexpire:
  topic: __keyevent@${spring.redis.database}__:expired