spring:
  rabbitmq:
    addresses: amqp://mq.jshuii.com:5672
    username: milisong-bposuser
    password: rh6D1LGtZlg16NK05i
  cloud:
    stream:
      # 设置默认的binder
      default-binder: pos
      binders:
        scm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-scm-breakfast
        pos:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-pos-breakfast
        oms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: milisong-oms