spring:
  rabbitmq:
    addresses: amqp://mqdev.jshuii.com:5672
    username: milisong-ecmuser
    password: ZqqA610ql0VK
  cloud:
    stream:
      # 设置默认的binder
      default-binder: ecm
      binders:
        ecm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到ecm的host和exchange
                virtual-host: milisong-ecm-breakfast
        scm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到scm的host和exchange
                virtual-host: milisong-scm-breakfast
        scm_lun:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到scm的host和exchange
                virtual-host: milisong-scm
        oms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到oms的host和exchange
                virtual-host: milisong-oms
      bindings:
        # 全局配置和门店属性配置
        config_input:
          binder: scm
          destination: SCM_CONFIG_PROPERTY
          group: ecm_breakfast_group
        # 截单配置
        config_intercept_input:
          binder: scm
          destination: SCM_CONFIG_INTERCEPT
          group: ecm_breakfast_group
        # banner配置
        config_banner_input:
          binder: scm
          destination: SCM_CONFIG_BANNER
          group: ecm_breakfast_group
        # 支付后用户通知
        notify_payment_input:
          binder: oms
          destination: OMS_PAYMENT
          group: ecm_breakfast_notify_group
        # 支付后用户地址更新
        user_payment_input:
          binder: oms
          destination: OMS_PAYMENT
          group: ecm_breakfast_user_group
        # 送餐送达后ivr电话回调结果
        ivr_input:
          binder: scm
          destination: SCM_IVR
          group: ecm_breakfast_group
        # scm公司信息
        company_input:
          binder: scm
          destination: SCM_COMPANY
          group: ecm_breakfast_group
        # 档期数据
        movie_input:
          binder: scm
          destination: SCM_BREAKFAST_GOODS_SCHEDULE
          group: ecm_breakfast_group
        # 可售商品数据
        salable_goods_input:
          binder: scm
          destination: SCM_BREAKFAST_GOODS_SALABLE
          group: ecm_breakfast_group
        # 商品基础数据
        goods_basic_input:
          binder: scm
          destination: SCM_BREAKFAST_GOODS_BASIC
          group: ecm_breakfast_group
        # 类目数据
        catalog_input:
          binder: scm
          destination: SCM_GOODS_CATEGORY
          group: ecm_breakfast_group
        # 顺风送达后微信、短信通知
        notify_arrive_input:
          binder: scm_lun
          destination: SCM_SF_STATUS_CHANGE
          group: ecm_breakfast_group
      rabbit:
        bindings:
          config_input:
            consumer:
              exchangeType: topic
              binding-routing-key: '#.ecm.#'
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_CONFIG_DLX
          config_intercept_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_CONFIG_INTERCEPT_DLX
          config_banner_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_CONFIG_BANNER_DLX
          notify_payment_input:
            consumer:
              bindingRoutingKey: '0'
              exchangeType: topic
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: OMS_NOTIFY_PAYMENT_DLX
              deadLetterQueueName: OMS_NOTIFY_PAYMENT_DLX_BF
              deadLetterRoutingKey: '0'
          user_payment_input:
            consumer:
              bindingRoutingKey: '0'
              exchangeType: topic
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: OMS_USER_PAYMENT_DLX
              deadLetterQueueName: OMS_USER_PAYMENT_DLX_BF
              deadLetterRoutingKey: '0'
          ivr_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_IVR_DLX
          company_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_COMPANY_DLX
          movie_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_MOVIE_DLX
          salable_goods_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_SALABLE_DLX
          goods_basic_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_GOODSBASIC_DLX
          catalog_input:
            consumer:
              exchangeType: fanout
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: SCM_CATALOG_DLX
          notify_arrive_input:
            consumer:
              exchangeType: topic
              autoBindDlq: true
              republishToDlq: true
              binding-routing-key: '0'
              deadLetterExchange: SCM_SF_STATUS_CHANGE_DLX