server:
  port: 39000
management:
  health:
    defaults:
      enabled: false

ribbon:
  ReadTimeout:  10000
  SocketTimeout:  1000

wechat:
  query-breakfast-accesstoken: http://mls-bapi.jshuii.com/v1/miniapp/query-accesstoken

upms:
  config:
    url: http://mls-upmsapi.jshuii.com
    app-name: MLB
    upmsUserInfoUrl: ${upms.config.url}/auth/userinfo
    upmsTokenUrl: ${upms.config.url}/auth/token
    upmsCheckLoginUrl: ${upms.config.url}/auth/check-login
    upmsCheckPermissionUrl: ${upms.config.url}/auth/check-permission
    upmsGetMenuListUrl: ${upms.config.url}/auth/menu
    upmsGetDataPermissionUrl: ${upms.config.url}/auth/data-permission
  filter-url:
    notHeadTokenUrls: /v1/qrcode/download-qrcode

spring:
  boot:
    admin:
      client:
        url: http://172.16.14.60:60100
        instance:
          prefer-ip: true