server:
  port: 30040

spring:
  boot:
    admin:
      client:
        url: http://localhost:60100
        instance:
          prefer-ip: true
        auto-deregistration: true
  cloud:
    config:
      override-none: true
#  zipkin:
#    base-url: http://localhost:60050
  sleuth:
    sampler:
      probability: 1
    
ribbon:
  ReadTimeout:  10000
  SocketTimeout:  10000

oms:
  sys:
    scmBaseUrl: http://devmls-dmsapi.jshuii.com
    delayQueue:
      orderCallbackUrl: http://devmls-omsapi.jshuii.com/v1/order/expired-order-cancel
      virtualOrderCallbackUrl: http://devmls-omsapi.jshuii.com/v1/order/expired-virtual-order-cancel
      baseUrl: http://devmls-dqsapi.jshuii.com
    localCache:
      expireTime: 1

scm:
  sys:
    scmBfRedisUrl: http://devmls-bscmapiin.jshuii.com/redis/get
    scmBfRedisUrlincr: http://devmls-bscmapiin.jshuii.com/redis/incr
    scmBfRedisUrlset: http://devmls-bscmapiin.jshuii.com/redis/set
# sms通知
sms:
  send-url: http://testsms.jshuii.com/api/v1/MobileSendService/sendSms
  out-of-stock-msg: 亲，很抱歉今天部分商品缺货，暂时用其他商品给您替代。我们将在24小时内为您退款，感谢您的谅解！
  send-time: "07:30"

shopservice:
  shopIdOne: 1
  shopIdTwo: 1797400023859200