server:
  port: 30010

# spring admin检测 默认开启
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    db:
      enabled: true
    redis:
      enabled: true
    rabbit:
      enabled: true
    diskspace:
      enabled: true

spring:
  boot:
    admin:
      client:
        url: http://172.16.14.60:60100
        auto-deregistration: true
        instance:
           prefer-ip: true
  flyway:
    # 配置sql脚本路径
    locations: classpath:/db/migration
    baseline-on-migrate: true

ribbon:
  ReadTimeout:  5000
  SocketTimeout:  1000

# 顺丰配置
sf:
  dev-id: 1520873106
  key: f601c556a93a872361fbdf268e5a4fa8
  version: 17
  base-url: https://commit-openic.sf-express.com/open/api/external
  create-order-url: ${sf.base-url}/createorder?sign=
  rider-h5-view: ${sf.base-url}/riderh5view?sign=
  notify-mobile: 18116246668,15000504458,18321399673,15002169809
  notify-mail: waimaichaoshi@jshuii.com
  over-time: 15
  test-flag: false
  lunch-weight: 420
  bf-weight: 100

dada:
  app-key: dada7cb14c7d6b59319
  app-secret: 0e74606b3d71b6a3cb7f3b61e110bdde

# 压缩url
url:
  compress-url: http://api.weibo.com/2/short_url/shorten.json?source=2849184197&url_long={url}

scm:
  query-lunch-by-order-no-url: http://ml-oss.jshuii.com/orderset/get-order-set-by-order-no?orderNo={orderNo}
  query-lunch-by-set-id-url: http://ml-oss.jshuii.com/orderset/query-detail-order-info?detailSetNo={detailSetNo}&detailSetId={detailSetId}
  query-bf-by-order-no-url: http://ml-oss.jshuii.com/orderset/get-order-set-by-order-no?orderNo={orderNo}
  query-bf-by-set-id-url: http://ml-oss.jshuii.com/orderset/query-detail-order-info?detailSetNo={detailSetNo}&detailSetId={detailSetId}
  query-all-shop-url: http://mls-scmapiin.jshuii.com/shop/get-all-shop-list
  query-shop-by-id-url: http://mls-scmapiin.jshuii.com/shop/query-by-id?id={id}
  query-building-url: http://mls-scmapi.jshuii.com/building/get-building-by-id?id={id}
  query-company-url: http://mls-scmapiin.jshuii.com/company/inside-query-by-id?id={id}
# sms通知
sms:
  sendUrl: http://sms.jshuii.com/api/v1/MobileSendService/sendSms
# 邮件通知
mail:
  send-url: http://email.jshuii.com/v1/emailService/sendSimpleMail
# 延迟队列时间
bf:
  orderset:
    delay: 60
