spring:
  rabbitmq:
    addresses: amqp://mq.jshuii.com:5672
    username: milisong-bscmuser
    password: zU0qOHksBYj26O5m11
  cloud:
    stream:
      # 设置默认的binder
      default-binder: scm
      binders:
        scm:
          type: rabbit
          environment:
           spring:
             rabbitmq:
               # 连接到scm的host和exchange
               virtual-host: milisong-scm
        dms:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到dms的host和exchange
                virtual-host: milisong-scm-breakfast